name: Build 8BP Pro Tool EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed main.py ^
        --add-data "models/best.pt;models"

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 8BP-Pro-Tool
        path: dist/*.exe
