name: Build 8BP Pro Tool EXE

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # ================= CODE =================
    - name: Checkout Repository
      uses: actions/checkout@v3

    # ================= PYTHON =================
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # ================= INSTALL =================
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # ================= CHECK MODEL =================
    - name: Verify Model
      run: |
        if (-Not (Test-Path "models/best.pt")) {
          Write-Host "ERROR: missing model"
          exit 1
        }

    # ================= BUILD EXE =================
    - name: Build EXE (PyInstaller)
      run: |
        pyinstaller --noconfirm --onefile --windowed main.py `
        --add-data "models/best.pt;models" `
        --hidden-import win32gui `
        --hidden-import win32con `
        --hidden-import win32api `
        --collect-all pywin32

    # ================= UPLOAD =================
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: 8BP-Pro-Tool
        path: dist/*.exe
